// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mllodcpzjmcniuaqodaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sbG9kY3B6am1jbml1YXFvZGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzY1NzgsImV4cCI6MjA3MDc1MjU3OH0.78Ue8bAZBzyYTKgH8sW1IiCuqHdVs2IQPQJ4zZ3AomE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});